# Starter pipeline
- task: AzureVmssDeployment@0
  inputs:
    azureSubscription: 'Microsoft Azure (1c11305e-cc14-45f0-a3ce-2e50b0cc5d41)'
    action: 'Update image'
    vmssName: 'sip2vmsstest'
    vmssOsType: 'Linux'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
